CSL 13 - PCA - Added Licence holder details and address page
UKHomeOffice/controlled-substance-licence pull request #7
Opened 2024-11-20 09:33 UTC by vinodhasamiyappanHO

## What? 
- [CSL-13](https://collaboration.homeoffice.gov.uk/jira/browse/CSL-13) - PCA - Licence holder details ('about the applicants' section)

## Why? 
- Creating new pages for precursor chemicals new applications.  Added Licence holder details and address page

## How? 
- Added necessary step configuration and field specific variables.
- Added required field validation for all pages

## Testing?
## Screenshots (optional)

## Anything Else? (optional)

## Check list
- [x] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [x] I have written tests (if relevant)
- [x] I have created a JIRA number for my branch
- [x] I have created a JIRA number for my commit
- [x] I have followed the chris beams method for my commit https://cbea.ms/git-commit/
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093a6e)
- [x] Ensure drone builds are green especially tests
- [x] I will squash the commits before merging

2024-11-20 15:03 UTC, RobertMcCann commented on apps/precursor-chemicals/sections/summary-data-sections.js
I also just noticed that the addresses for this form are joined together by `,` and not \n

2024-11-20 15:04 UTC, RobertMcCann commented on apps/precursor-chemicals/sections/summary-data-sections.js
It seems inconsistent to me actually so I'm not too sure 

![Screenshot 2024-11-20 at 15 04 06](https://github.com/user-attachments/assets/9f34d02e-ff2d-4655-8e2c-b69b822ee142)

2024-11-20 15:07 UTC, dk4g requested changes
there are  some indentations (4 spaces) which needs to be change to (2 spaces)

2024-11-20 15:07 UTC, dk4g commented on apps/precursor-chemicals/translations/src/en/validation.json
> +        "notUrl": "Your answer must not contain URLs or links",
`notUrl` redundant, as mentioned earlier

2024-11-20 15:09 UTC, dk4g commented on apps/precursor-chemicals/sections/summary-data-sections.js
let's keep it `\n` for now, I will raise this with UCD

2024-11-20 15:18 UTC, dk4g commented on apps/precursor-chemicals/fields/index.js
> +    validate: ['required', 'notUrl'],
worth adding a comment here too
`// additional validation covered in custom-validation.js`

2024-11-20 18:45 UTC, dk4g commented on apps/precursor-chemicals/translations/src/en/validation.json
> +}
No newline at end of file

2024-11-20 20:06 UTC, dk4g approved these changes

2024-11-21 09:42 UTC, vinodhasamiyappanHO commented on apps/precursor-chemicals/sections/summary-data-sections.js
Its updated

2024-11-21 11:29 UTC, RobertMcCann approved these changes
Looks good to me!

2024-11-21 12:23 UTC, merged